apiVersion: v1
appVersion: 3.0.0
description: nfs-server-provisioner is an out-of-tree dynamic provisioner for Kubernetes. You can use it to quickly & easily deploy shared storage that works almost anywhere.
name: nfs-server-provisioner
version: 1.5.0
maintainers:
- name: kiall
  email: kiall@macinnes.ie
- name: kvaps
  email: kvapss@gmail.com
- name: joaocc
  email: joaocc-dev@live.com
home: https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner
sources:
- https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/tree/HEAD/charts/nfs-server-provisioner
keywords:
- nfs
- storage
